spring:
  datasource:
    url: jdbc:postgresql://zerone-network.ru:5432/skillbox?stringtype=unspecified
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

microservices:
  host: zerone-network.ru
